name: Build Geode Mod

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: Win64

  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: Mac

  build-android32:
    name: Android32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: Android32

  build-android64:
    name: Android64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: Android64
